// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtoueyqqtnifgxmrzbwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0b3VleXFxdG5pZmd4bXJ6Ynd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjIwNjIsImV4cCI6MjA2NTUzODA2Mn0.B9aR1dpVmiX9oMaHkG9PxdanZv-JXtwgTO-XWgXVok0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);