"""add_gender_age_to_player

Revision ID: a018f34c26a9
Revises: f63a80fe79d2
Create Date: 2026-03-04 00:09:23.138624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a018f34c26a9'
down_revision: Union[str, Sequence[str], None] = 'f63a80fe79d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('players', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'age')
    op.drop_column('players', 'gender')
    # ### end Alembic commands ###
