"""add batch to player

Revision ID: f63a80fe79d2
Revises: 21cdd99b3dbc
Create Date: 2026-03-03 23:34:51.869593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63a80fe79d2'
down_revision: Union[str, Sequence[str], None] = '21cdd99b3dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('batch', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'batch')
    # ### end Alembic commands ###
